language: ruby
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails41.gemfile
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
  - 2.1.0
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
